# Generated by Django 4.0.1 on 2022-03-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serveur',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=None)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
