# Generated by Django 4.0.1 on 2022-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_serveur'),
    ]

    operations = [
        migrations.CreateModel(
            name='boissonschaudes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='boissonsfraiches',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='carte',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='crepes',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='glaces',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='jus',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desceription', models.TextField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('rate', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='serveur',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
