# Generated by Django 4.0.1 on 2022-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_boissonschaudes_desceription'),
    ]

    operations = [
        migrations.CreateModel(
            name='comande',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('listitem', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lignecommande',
            fields=[
                ('produits', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
