# Generated by Django 4.0.1 on 2022-03-26 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lignecommande_remarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='comande',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 27)),
        ),
        migrations.AlterField(
            model_name='comande',
            name='time',
            field=models.TimeField(default=datetime.time(0, 20, 48, 810685), primary_key=True, serialize=False),
        ),
    ]
